- name: create vault directories
  file: >
    state=directory
    path={{ item }}
    owner={{ consul_user }}
    group={{ consul_group }}
  with_items:
    - "{{ vault_home }}"
    - "{{ vault_home }}/bin"
    - "/etc/vault"

- name: install vault
  # Skip lint for this, ansible does not have an easy way to download and extract file to location in a succinct manner
  # noqa 303
  shell: >
    curl -L {{ vault_url }} -o /tmp/vault.zip &&
    unzip /tmp/vault.zip -d "{{ vault_home }}/bin/" &&
    rm -rf /tmp/vault*
  args:
    creates: "{{ vault_home }}/bin/vault"

- name: set ownership
  file: >
    state=directory
    path={{ vault_home }}
    owner={{ consul_user }}
    group={{ consul_group }}
    recurse=yes

- name: vault symlink to /usr/local/bin
  file: src={{ vault_home }}/bin/vault dest=/usr/local/bin/vault owner=root group=root state=link
