---
scala_version: "2.12"
kafka_version: "2.3.1"
full_version: "kafka_{{ scala_version }}-{{ kafka_version }}"
kafka_url: "https://archive.apache.org/dist/kafka/{{ kafka_version }}/{{ full_version }}.tgz"
