---

# TODO: Redo this. there's no reason this should be a docker container other than your laziness.

#- name: ensure docker is stopped if running on Amazon because we use chroot bindmount
#  systemd:
#    name: docker
#    state: stopped
#  when: ansible_distribution == 'Amazon'

- name: pull docker registrator image
  docker_image:
    pull: yes
    name: "{{ registrator_docker_image }}"

- name: save registrator image to tar since /mnt is wiped
  command: "/usr/bin/docker save -o /root/registrator.tar {{ registrator_docker_image }}"

- name: copy registrator setup script
  template:
    src: opt/ivy/setup_registrator.sh.j2
    dest: /opt/ivy/setup_registrator.sh
    mode: 0755
