- name: add mongodb repo
  yum_repository:
    name: mongodb-org-4.0
    description: MongoDB Repository
    baseurl: https://repo.mongodb.org/yum/redhat/7/mongodb-org/4.0/x86_64/
    gpgcheck: yes
    gpgkey: https://www.mongodb.org/static/pgp/server-4.0.asc

- name: add pritunl repo
  yum_repository:
    name: pritunl
    description: Pritunl Repository
    baseurl: https://repo.pritunl.com/stable/yum/centos/7/
    gpgcheck: yes

- name: trust pritunl key
  rpm_key:
    key: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x7568D9BB55FF9E5287D586017AE645C0CF8E292A
    state: present

- name: install packages
  yum:
    name:
      - "pritunl-{{ pritunl_version }}"
      - mongodb-org
    state: present

- name: disable pritunl on first boot
  service:
    name: pritunl
    enabled: no
    state: stopped
