---
# Import tasks for the specific OS being built
- include: "{{ ansible_distribution }}.yml"

- name: trust pritunl key
  rpm_key:
    key: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x7568D9BB55FF9E5287D586017AE645C0CF8E292A
    state: present

- name: install packages
  yum:
    name:
      - "pritunl-{{ pritunl_version }}"
      - mongodb-org
    state: present

- name: disable pritunl on first boot
  service:
    name: pritunl
    enabled: no
    state: stopped
